### PR TITLE
Switching to uv (attempt 2)

### PR DESCRIPTION
**Pull request by apoorvkh**
uv has better support for installing PyTorch, since 0.5.0 (https://github.com/astral-sh/uv/pull/8797)

I tried to switch from pixi to uv earlier (#75) but ran into several issues. But it works now!

Simply `uv sync` to build the virtual environment, then `source .venv/bin/activate` to activate.

Switched the CI pipeline to UV as well.

### CODE REVIEW

**Comment by pmcurtin** [comment]
I had the following error trying to do `uv sync`:
```
(default) peter@ubuntu-69:~/Desktop/torchrunx$ uv sync
warning: Failed to parse `pyproject.toml` during settings discovery:
  TOML parse error at line 32, column 1
     |
  32 | [project.urls]
     | ^
  invalid table header
  duplicate key `urls` in table `project`

error: Failed to parse: `pyproject.toml`
  Caused by: TOML parse error at line 32, column 1
   |
32 | [project.urls]
   | ^
invalid table header
duplicate key `urls` in table `project`
```

This was fixed by commenting out line 14 of `pyproject.toml`... Did you encounter this issue?

**Comment by apoorvkh** [comment]
I think you should only have one of `[project.urls]` (line 32 above) or `urls = { ... }` (line 14 that you are mentioning) in this file. Does your repo have unresolved merge conflicts (in `pyproject.toml`)?

**Comment by apoorvkh** [comment]
I only see one instance of `urls` here: https://github.com/apoorvkh/torchrunx/blob/uv-v2/pyproject.toml

**Comment by pmcurtin** [comment]
Yeah I was simply on the wrong branch lmao, there's no issue

**Review by pmcurtin — APPROVED** [review]
looks good and works fine!

**Pull request merged**
