### PR TITLE
examples to tests

### PR DESCRIPTION
**Pull request by pmcurtin**
#42

### CODE REVIEW

**Comment by pmcurtin** [comment]
I'll be adding more tests to cover error cases.

**Comment by pmcurtin** [comment]
Actually let me resolve the conflict before reviewing.

**Comment by apoorvkh** [comment]
I think we use `submitit` and `transformers` for extra testing. Should make a pixi environment for extras.

**Comment by pmcurtin** [comment]
@apoorvkh Alright, this is finished for now. Probably be good to flush out a few more CI tests eventually, but I'd like to merge this so we can finish up and go for a beta release.

**Review by apoorvkh — APPROVED** [review]
LGTM

**Pull request merged**
